### ISSUE TITLE
https not working

### ISSUE THREAD

**Issue by zetiv** [codazoda/nolific#1]
I getting error when trying https://localhost:8001 on Firefox

`Invalid request (Unsupported SSL request)`

**Comment by codazoda** [comment]
Thanks so much for pointing that out.

I'd like to run Nolific over https but the PHP built-in server, which I explain how to use, doesn't support https. So, the easy fix, for now, is to change the example URL to _http_. I'd have to front Nolific with something like nginx to fix this for real and that's probably outside the scope of the little project.

Here's the commit that fixes the readme.

https://github.com/codazoda/nolific/commit/21622219e7ef144424743327deb0cf298517792e
