### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by zetiv** [codazoda/nolific#2]
- In README  i dont see that SQLite is required but I'm getting an error on home page
  `PHP Fatal error:  Uncaught Error: Class 'SQLite3' not found`
  Installing `apt-get install php7.4-sqlite3` fixes the problem

- Username/PSW info is missing

**Comment by codazoda** [comment]
Thanks for the bug report. I've added a tiny bit of information to a _Requirements_ section in the readme.

Here's the commit.

https://github.com/codazoda/nolific/commit/9d017a282a342e2c40d5ea85e21a02f2fd619368

**Comment by codazoda** [comment]
Note that I didn't address the username/psw concern. There's another issue for that (also created by zetiv) so I'll address it in that issue. https://github.com/codazoda/nolific/issues/3
