### ISSUE TITLE
Typo in project website splash image

### ISSUE THREAD

**Issue by samelawrence** [codazoda/nolific#4]
*Expected*
"plain-text"

*Observed*
"plaint-text"

![Screen Shot 2022-01-31 at 2 57 43 PM](https://user-images.githubusercontent.com/170246/151863955-dd8f3d7a-37bd-4121-b00e-051651dc468d.png)

**Comment by codazoda** [comment]
Thanks for the issue report. I've fixed the screenshot (it will try to be cached so might take a hard refresh).
